### ISSUE TITLE
Seasons thumb preview shows posters.png and not actual thumb

### ISSUE THREAD

**Issue by dcplaya** [ecleese/plexWatchWeb#108]
Line 104 in info.php does not correctly pull the thumb preview of the season for that show. It currently just shows the default posters.png

Still trying to track down a fix (I'm new to PHP/XML)

Edit: This is in version 1.7.0

**Comment by Arcanemagus** [comment]
Created a PR that fixes this, I'm pretty sure that was in the original code (it just displayed a broken image instead of the default one), but it's also entirely possible I broke it in the re-write :wink:.

**Comment by dcplaya** [comment]
It was broken in the original code (v 1.6.0) too! It displayed a broken image instead of the default.png though. You made progress but didn't fix is completely. Testing your PR and it works correctly!
