### ISSUE TITLE
Once the initial settings are entered, settings page shows nothing

### ISSUE THREAD

**Issue by dcplaya** [ecleese/plexWatchWeb#110]
Once the setting are entered at first startup, the settings page no longer shows any setting options, just the section list on the far left. See below attached picture.
![2015-06-01 13_33_30-plexwatch](https://cloud.githubusercontent.com/assets/1105320/7918922/db4edd60-0862-11e5-993d-79529cd7751c.jpg)

Deleting config.php allows settings to be set again but then disappears as soon as settings are saved.

**Comment by Arcanemagus** [comment]
Make sure the user your web server is running as has write access to the `config` directory in the plexWatch folder. I'm not sure it currently checks for errors during writing. I'll test this myself later today.

**Comment by dcplaya** [comment]
I just made the config folder and config.php RWX to all users (```chmod 777```) and still the same result 

If it doesnt have write access, I get an error saying something like "unable to write to ./config/config.php". Once I gave www-data write access, I could save the settings but after the initial save, the page shows what I attached above.

**Comment by Arcanemagus** [comment]
Looks like this is caused by an invalid plexWatch database location setting, looking into why something more helpful isn't given to the user.

**Comment by Arcanemagus** [comment]
That should fix things up for you :wink:
Error handling needs a serious overhaul, this is just the first few steps.

**Comment by dcplaya** [comment]
This is much better because it shows the error now but still unable to fix the error!  The actual settings still do not show up. See below

![image](https://cloud.githubusercontent.com/assets/1105320/7935159/9a6b7caa-08fc-11e5-9d86-2090ca0ec7fc.png)

**Comment by Arcanemagus** [comment]
Did you grab both commits? The first one gets you to the stage you have screenshotted above where the error is reported back to the client, the second one blocks you from saving the settings and sends you back to the screen if the database file doesn't exist.

(If you specify a file that exists, but isn't a database you currently get no error, but at least can access the settings screen and see that it has no version for plexWatch.)

**Comment by dcplaya** [comment]
Ah you are correct. That screenshot above is of a config.php file from the old version. So if a user manually edits the config.php file with faulty db location, that shows up.

But if the user edits the settings via the webpage like they should, they get the following.
![image](https://cloud.githubusercontent.com/assets/1105320/7939698/488e7a2c-091a-11e5-9385-869054bfc86b.png)

**Comment by Arcanemagus** [comment]
Yep, not much (currently) that can be done for pre-broken config files :smirk:

I'm planning on completely re-writing how the settings are done (https://github.com/Arcanemagus/plexWatchWeb/issues/1) but haven't gotten around to it yet.
