### ISSUE TITLE
Friendly User names not showing up

### ISSUE THREAD

**Issue by rjsears** [ecleese/plexWatchWeb#130]
Utilizing PlexWatch 0.3.3-DEV and friendly names enabled:

User: Richard Sears [rsears]
 Wed Jun 10 16:21:02 2015: Richard Sears playing Hide and Seek [T] [2005] [R] [1 hour and 41 minutes] on Xbox 360 for 4 minutes [19%] [1 hour and 22 minutes left] 72.208.x.x

However on PlexWatchWeb, interface is showing plex username instead of friendly name. 

![screen shot 2015-06-10 at 4 26 42 pm](https://cloud.githubusercontent.com/assets/12837199/8096587/970144c2-0f8d-11e5-9c57-a14a168e0222.png)
![screen shot 2015-06-10 at 4 26 57 pm](https://cloud.githubusercontent.com/assets/12837199/8096588/97038764-0f8d-11e5-96bd-d526f5ada783.png)

**Comment by Arcanemagus** [comment]
The second picture is from one of the history views, which looks like it is broken and needs to be fixed. Your first picture looks to be from the Activity section which _should_ be working.

Can you edit the `includes/functions.php` file and add a line after line 35 so it looks like this:
```php
	if (is_object($config)) {
		$friendlyName = $config->{'user_display'};
var_dump($friendlyName);
		if (is_object($friendlyName)) {
```

This will make the activity screen spit out the list of Friendly names it is getting from the plexWatch database, ensure that your user name is one of the keys in there?
You should see output like this:
```
object(stdClass)#4 (16) {
  ...
  ["arcanemagus"]=>
  string(6) "Landon"
  ...
}
```

(It might be easier to see that if you hit Ctrl+Shift+I to open debugging tools, go to the network tab, and then click on the `current_activity.php` line.

**Comment by rjsears** [comment]
OK I did that and here is now what I see:

    object(stdClass)#26 (5) { ["real_user2"]=> string(12) "Rob & Carrie" ["real_user1"]=> string(5) "Frank" ["real_user2+roku 3"]=> string(11) "Family Room" ["real_user2+ios"]=> string(3) "Rob" ["real_user2+roku"]=> string(11) "Family Room" } bphoover is watching Home
![screen shot 2015-06-10 at 6 27 43 pm](https://cloud.githubusercontent.com/assets/12837199/8097971/6fc4cd00-0f9e-11e5-8efc-3a724a5dcf4e.png)


This is very interesting. I am not sure where it is getting that info (real_user2+ois), etc as this is what my config looks like:

    /opt/plexWatch/config.pl

    $user_display = {'rsears' => 'Richard Sears',
                 'rsears+My SM-T330NU' => 'Freddie Manuel',
                 'SMPxOne' => 'Ryan Miller',
                 'bdavis008' => 'Becky Davis',
                 'Bphoover' => 'Bill Hoover',
};


and


    root@cinaplex:/var/www/html# /opt/plexWatch/plexWatch.pl --watching

======================================= Watching ========================================

    User: Bill Hoover [Bphoover]
     Wed Jun 10 17:51:41 2015: Bill Hoover playing Home [D] [2015] [PG] [1 hour and 34 minutes] on     Roku 2 for 38 minutes [100%] [1 second left] 68.111.167.113

    User: Richard Sears [rsears]
     Wed Jun 10 17:51:47 2015: Richard Sears playing Easy A [T] [2010] [PG-13] [1 hour and 32     minutes] on Plex for Sony (PlayStation 4 01.17) for 38 minutes [74%] [24 minutes left] 76.176.65.191
     Wed Jun 10 17:51:48 2015: Richard Sears playing The Skeleton Twins [T] [2014] [R] [1 hour and    33 minutes] on Xbox 360 for 38 minutes [43%] [53 minutes left] 10.0.3.21
     Wed Jun 10 18:14:55 2015: Richard Sears playing Battle of Britain [T] [1969] [G] [2 hours and 12 minutes] on Plex for Vizio (Vizio MTK) for 15 minutes [15%] [1 hour and 53 minutes left] 71.87.193.113

**Comment by Arcanemagus** [comment]
This looks like it's an issue with plexWatch, the user mapping that plexWatch/Web is getting from the plexWatch database is the example mappings from the config.pl-dist file. Since it is giving you the proper names from the command line it looks like _it_ is using the proper names... just not storing them in the database.

Just to confirm, can you run the following command:
```
sqlite3 /opt/plexWatch/plexWatch.db "SELECT json from config;"
```
Somewhere in the output of that there should be a "user_display" object that contains the proper mappings, but looks (at least from the pW/W output) like it hasn't been updated.

**Comment by timrettop** [comment]
@Arcanemagus It could also be the PHP session token is storing the previous config.  

Thats the case for me, as I have the correct config in plexwatch, and trying a previously unused browser shows the friendly names. 

I guess that the session config should be periodically cleared in this function, but I'm not sure how often.

```
/* Either load or return the plexWatch config
 * we might want to time this at some point.
 * If a user doesn't close the browser, this will never update
 */
function loadPwConfig() {
        if (!isset($_SESSION['pwc'])) {
                $database = dbconnect();
                $query = "SELECT json from config";
                $result = getResults($database, $query);
                if ($result = $result->fetchColumn()) {
                        if ($json = json_decode($result)) {
                                $_SESSION['pwc'] = keysToLower($json);
                        }
                }
        } else {
                return $_SESSION['pwc'];
        }
}
```

**Comment by Arcanemagus** [comment]
Ah, that would do it too. I'm running into similar issues with the PMS URL, that whole setup needs to be revamped.

**Comment by rjsears** [comment]
I think it was the PHP session token. Once I used a different computer, this is what I show now (Correctly):

![screen 2015-06-10 at 7 33 57 pm](https://cloud.githubusercontent.com/assets/12837199/8098689/fe8d5a58-0fa7-11e5-9be6-bbe718a31852.jpg)

**Comment by Arcanemagus** [comment]
You can clear that by deleting the PHPSESSID cookie on any computer still having issues. I'll work on a better method of caching data on the server side. (This particular use case may be served by client side JS that is already in place.)

**Comment by rjsears** [comment]
It looks like the only place it is not working now is the history tab (not sure it is supposed to work there actually):

![screen 2015-06-10 at 8 01 41 pm](https://cloud.githubusercontent.com/assets/12837199/8098975/a5919e2e-0fab-11e5-8700-74a4c514119f.jpg)

**Comment by Arcanemagus** [comment]
It isn't currently, which is why the issue is still open :wink:.

**Comment by rjsears** [comment]
Understood! Thanks

**Comment by Arcanemagus** [comment]
That should do it for you, please update your copy of the dev branch and see if you have any issues. If so feel free to re-open this :wink:.

**Comment by timrettop** [comment]
This works great for me!   Thanks

**Comment by rjsears** [comment]
This worked! Thank you!

**Comment by rjsears** [comment]
Well, something new cropped up once I moved to the new DEV tree. Not sure if it is related or not. I am getting no history now from the server - it sits continuously at the "Loading Data from Server" prompt.

![screen 2015-06-11 at 1 25 04 pm](https://cloud.githubusercontent.com/assets/12837199/8117544/d0145348-103d-11e5-86ca-b37373ccf3f4.jpg)

**Comment by Arcanemagus** [comment]
Can you file a new issue about that @rjsears?

**Comment by rjsears** [comment]
Done!

https://github.com/ecleese/plexWatchWeb/issues/135
