### ISSUE TITLE
Enhancement: Friend's recently added

### ISSUE THREAD

**Issue by timrettop** [ecleese/plexWatchWeb#133]
I think that it would be fantastic to be able to get a list of my friends recently added media, as it'd be a quick way to see whats new in everyone's libraries. 

I can understand that this might be fairly long process to query all the friends and fetch their lists and thumbnails, so maybe its an optional setting,  but what do you think? 

Maybe some caching of the images so that re-checks are quicker?

**Comment by Arcanemagus** [comment]
I don't think this is actually possible, when you see this information from the plex.tv interface the data for how to talk to that server is coming from plex.tv. Querying a server directly doesn't give you any information on friend's servers as far as I can tell from looking over https://code.google.com/p/plex-api/wiki/PlexWebAPIOverview and my own testing.

Support for this is probably better dealt with as part of https://github.com/ecleese/plexWatchWeb/issues/76.
