### ISSUE TITLE
Failed to retrieve... (Latest Dev)

### ISSUE THREAD

**Issue by markaswift** [ecleese/plexWatchWeb#137]
When I access the PlexWatch page on the latest Dev I get the following errors:

Failed to retrieve "/status/sessions?X-Plex-Token=xxx"
Failed to retrieve "/status/sessions?X-Plex-Token=xxx"
Statistics
Failed to retrieve "/library/sections?X-Plex-Token=xxx"
Recently Added
Failed to retrieve "/library/recentlyAdded?X-Plex-Container-Start=0&X-Plex-Container-Size=7&X-Plex-Token=xxx"

I had this successfully up and running with the master build for sometime. I've tried recreating the config file, no luck.

**Comment by Arcanemagus** [comment]
That means it's having trouble talking to the PMS server, can you verify the settings are correct?

**Comment by drzoidberg33** [comment]
There is another bug here though as I see a bunch of errors are exposing the full server path and Plex token in the error message. I have seen the same on my end with thumbs that failed to load.

**Comment by brumle80** [comment]
Had same issue, disappeared when I emptied Chrome cache.
 12. jun. 2015 17.59 skrev "drzoidberg33" <notifications@github.com>:

**Comment by markaswift** [comment]
Cache... God damn it. Thank you!

**Comment by Arcanemagus** [comment]
@drzoidberg33 Yea I noticed that as well, will have to remember to fix that before we (finally) update master...

@everyoneelse: Uggg, damn cache. That really needs work :frowning:

@markaswift Since this is resolved for you I'm closing this for now, thanks for submitting an issue!
