### ISSUE TITLE
History does not show correct user...

### ISSUE THREAD

**Issue by rjsears** [ecleese/plexWatchWeb#141]
Noticed another interesting thing with the history. On the main page, PlexWatchWeb shows the 'correct' user currently playing a video. Once that person stops playing that video and it goes into history, it does not show the same user. 
 
I am pretty sure I know why this is happening. plexWatch supports a username+device which I use to track the kids, etc (under my username). This shows up correctly when using /opt/plexwatch/plexwatch.pl --watched and it shows up correctly when the video is being played on plexWatchWeb, but not when it gets sent to the history section.
 
 
 
/opt/plexwatch/plexwatch.pl --watched
 
User: Freddie Manuel [rsears]
 Fri Jun 12 14:21:12 2015: Freddie Manuel watched Teen Titans - Apprentice (Part 1) - s01e12 [T] [2003] [22 minutes] [TV-Y7] on My SM-T330NU for 22 minutes [100%] 
 Fri Jun 12 14:43:12 2015: Freddie Manuel watched Teen Titans - Apprentice (Part 2) - s01e13 [T] [2003] [22 minutes] [TV-Y7] on My SM-T330NU for 25 minutes [100%] 
 
 
 
This is from my /opt/plexwatch/config.php:
 
 
$user_display = {'rsears' => 'Richard Sears',
                 'rsears+My SM-T330NU' => 'Freddie Manuel',
   };
 
 
Here are two screen shots, the first is of Freddie playing a teen titans movie and it shows up correctly as Freddie, the second was after he finished another teen titans movie, here it shows my user.
 
 
It correctly displays here:

![screen 2015-06-14 at 5 06 56 pm](https://cloud.githubusercontent.com/assets/12837199/8151156/ad19c33a-12ba-11e5-8d5e-3ab8094823f2.jpg)

But now here (after he was done watching the movie:

![screen 2015-06-14 at 5 09 28 pm](https://cloud.githubusercontent.com/assets/12837199/8151159/bc6025be-12ba-11e5-85e1-5a11acbd1964.jpg)

**Comment by Arcanemagus** [comment]
I'm looking into whether this is possible, the history pages unfortunately deal with data on an individual column basis, getting the correct name in this case needs access to data from multiple columns. I'll see how much of a hack will be needed to get data from a different column.

**Comment by rjsears** [comment]
Thanks

**Comment by Arcanemagus** [comment]
There you go! As always, re-open if it doesn't work properly for you.

**Comment by rjsears** [comment]
Thanks (as always)!
