### ISSUE TITLE
https added back into Plex

### ISSUE THREAD

**Issue by Ackis** [ecleese/plexWatchWeb#149]
Re: https://github.com/ecleese/plexWatchWeb/issues/81

They've added https support back.

**Comment by Arcanemagus** [comment]
And support was added the next day: https://github.com/ecleese/plexWatchWeb/pull/112 :stuck_out_tongue: 

Thanks for keeping an eye out though :wink:.

**Comment by Ackis** [comment]
Hah sorry = missed that somehow.
