### ISSUE TITLE
Receiving "Failed to access Plex Media Server. Please check your settings." on Home Screen after upgrading to Plex Pass

### ISSUE THREAD

**Issue by speedyflipper** [ecleese/plexWatchWeb#159]
After upgrade to plexpass, I am no longer able to see the home screen. Instead I receive "Failed to access Plex Media Server. Please check your settings."

No other settings have been changed. Every other page seems to be working fine

**Comment by Arcanemagus** [comment]
I've had reports that if you don't have Plex Pass the Plex server will accept _any_ token as valid authentication (We won't go into how bad of an idea that is here...). When you have Plex Pass though the token used to authenticate _must_ be valid.

Can you try going into the settings and re-saving your settings, ensuring your user/pass is the same?

If that doesn't work move your current settings to a different location (`config.php.bak`) and save them fresh.

**Comment by speedyflipper** [comment]
That seemed to have worked thanks

**Comment by Arcanemagus** [comment]
Thanks, closing.
