### ISSUE TITLE
Security Issue in setting.php

### ISSUE THREAD

**Issue by ShafferZee** [ecleese/plexWatchWeb#163]
The password value stored in the config.php should not be pulled into settings.php as a hidden placeholder. The password can easily be accessed by viewing the HTML source or by editing the type="password" tag to type="text".

settings.php Line 293

**Comment by Arcanemagus** [comment]
`config.php` doesn't store the password, or user for that matter... are you looking at the outdated `master` branch or the current `dev`?

**Comment by ShafferZee** [comment]
Apologies, I'm on the master branch.

**Comment by Arcanemagus** [comment]
Ah, marking this as closed then since the `master` branch will be being replaced with the `dev` when [v1.7](https://github.com/ecleese/plexWatchWeb/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.7) is done.
