### ISSUE TITLE
Images for shows/movies not appearing with Plex Home

### ISSUE THREAD

**Issue by AevumDecessus** [ecleese/plexWatchWeb#165]
Using plexWatchWeb with a server on another server, I am currently unable to see any pictures for shows/movies under recently added, watching now, etc. Inspecting the page, I see that it's receiving HTTP 500 errors for the images

```
GET http://192.168.1.25/includes/img.php?img=%2Flibrary%2Fmetadata%2F83194%2Fart%2F1438969271%26width%3D300%26height%3D169 500 (Internal Server Error)
```

Examining the apache logs, I find the following errors:

```
[Fri Aug 07 15:16:03.006746 2015] PHP Fatal error:  Failed to retrieve "https://192.168.1.22:32400/photo/:/transcode?url=http://127.0.0.1:32400/library/metadata/83194/art/1438969271&width=300&height=169" in /usr/local/www/apache24/data/includes/img.php on line 28, referer: http://192.168.1.25/index.php
```

Where 192.168.1.22 is the IP that the plex server is running on, and 192.168.1.25 is the IP that PlexWatch and PlexWatch/Web are running on.

Server: Freebsd 10.1-RELEASE
Webserver: Apache 2.4
plexWatch Version: v0.3.3-DEV
plexWatch/Web Version: 1.7.0

**Comment by Arcanemagus** [comment]
Did you change your Plex password?

**Comment by AevumDecessus** [comment]
Fresh install of the server and plexwatch. I changed my password when the breach happened but it hasn't changed since then.

**Comment by Arcanemagus** [comment]
Was it working before and just suddenly stopped?
Are there any firewalls between the two machines that might be blocking it?

**Comment by AevumDecessus** [comment]
I just found and installed plexWatch and plexWatch/Web for the first time, I have yet to see the images successfully.

There are no firewalls between the 2 boxes.

**Comment by Arcanemagus** [comment]
My guess is that your password is incorrect in the settings of plexWatchWeb, unfortunately it looks like it logs the same error message for invalid authentication, and an actual failure so I can't be sure.

If you remove the config.php file that was generated and save the settings again do they save successfully with your user/pass?

**Comment by AevumDecessus** [comment]
I deleted the config/config.php file, plexWatch/Web prompted me to set up the settings again, enter the fields for DB location, server location, plex username/password, and it saved successfully, including the plexAuthToken, It shows currently playing shows, information about what's on the plex server, and history, but still does not show images.

**Comment by Arcanemagus** [comment]
If you try to open the following link in a browser (On a different machine than the Plex server!) what do you get?
```
https://192.168.1.22:32400/photo/:/transcode?url=http://127.0.0.1:32400/library/metadata/83194/art/1438969271&width=300&height=169&X-Plex-Token=putYourTokenHere
```

Replace "putYourTokenHere" with a valid token of course :wink:.

**Comment by AevumDecessus** [comment]
That returns an HTTP 404 after an SSL certificate error (Server's certificate does not match the url).

**Comment by smokeofc** [comment]
I also have this problem. I have two computers running this plexwatch towards two servers, on one it works perfectly, on the other it doesn't show pictures.

**Comment by JigSawFr** [comment]
Same problem with a docker image on the same machine, all is working but not images

**Comment by Arcanemagus** [comment]
Removed the token from the log line, as it _could_ be used to gain unfettered access to your server if it is a valid token :stuck_out_tongue:.

@JigSawFr neither the current `dev` or `master` should produce an error message like that, looks like you might still be on an older version of the dev branch?

**Comment by JigSawFr** [comment]
@Arcanemagus oups sorry for token haha !
So, i've found why, i'm on plexWatch/Web Version: v1.5.4.2 & plexWatch Version: v0.3.3-DEV
And images have all an harcoded url in php files, an so many repeating lines \o/
It's better to use pmsIP params than 127.0.0.1 (not reachable for me)

**Comment by Arcanemagus** [comment]
The `dev` branch handles images entirely different than the `master` that you are currently on (for one thing the token is sent as a header instead of in the URL).

**Comment by justinriddoch** [comment]
I am having the same issue, the error I get when I right click and select 'View Image' on one of the Artwork locations is:

`The image “XXXXXX/plexWatch/includes/img.php?img=http%3A%2F%2F24.141.211.43%3A20897%2Fphoto%2F%3A%2Ftranscode%3Furl%3Dhttp%3A%2F%2F127.0.0.1%3A20897%2Flibrary%2Fmetadata%2F17439%2Fthumb%2F1482617701%26width%3D256%26height%3D352” cannot be displayed because it contains errors.`

**Comment by Arcanemagus** [comment]
@justinriddoch all development here has been stopped, please switch over to [PlexPy](https://github.com/JonnyWong16/plexpy) for your server monitoring needs!
