### ISSUE TITLE
Time?

### ISSUE THREAD

**Issue by DereckR** [ecleese/plexWatchWeb#171]
The times are showing way off like 6am and the times are way off?

**Comment by Arcanemagus** [comment]
This project uses the time zone as configured in your `php.ini`, the first step I would go with would be to make sure that was correct.

**Comment by DereckR** [comment]
Ty sir that fixed itJ Was set to berlin

 

Thank You,

 

Dereck Radford

**Comment by Arcanemagus** [comment]
Marking as closed then, glad it was a simple fix :wink:.
