### ISSUE TITLE
stats.php line 242

### ISSUE THREAD

**Issue by trackermb** [ecleese/plexWatchWeb#172]
Hi there saw that the maxhourly plays chart was pulling DD MMM on the x Axis this can be fixed by copy line 214 and replacing line 242. Finished line should look like

return moment(x).format('<?php echo $settings->getTimeFormat(); ?>');

only issue i am having now is that it doesn't sort the hours in chronological order it just adds any new hours to the end 
![screen shot 2015-09-30 at 12 20 40 pm](https://cloud.githubusercontent.com/assets/7849892/10191646/ba43b478-676d-11e5-8bfe-0a507f825135.png)

![screen shot 2015-10-02 at 20 53 21](https://cloud.githubusercontent.com/assets/7849892/10256252/d9b2a7ca-6947-11e5-81c4-76257bf1cfd5.png)
as you can see theres 2 10pm's

Cheers 
Mark

**Comment by Arcanemagus** [comment]
Which file are you talking about?
Are you looking at the `dev` or `master` branches? The `master` branch is _very_ out of date if that is what you are currently using...

**Comment by Arcanemagus** [comment]
Ah, or I can read the title of the issue :stuck_out_tongue:. I'm assuming that you are on the `dev` branch based on the line numbers.

The `tickFormatX` only affects the display,  not the data so it should have no change on the sorting order. Your screenshot shows things sorted chronologically though so I'm not sure what you are trying to say here?

**Comment by trackermb** [comment]
Hi yes using Dev branch. What I mean is the chart should really start at night and have every hour regardless of an plays. 

Also I'm now getting this duplicate entries for a few hours.

**Comment by Arcanemagus** [comment]
Unfortunately the graphing library cuts out "empty" data points from what I remember of the last time I looked into this, so having it show all hours would be difficult at best, but probably involve switching to a different library.

What do you mean by "duplicate entries"? More than one entry for the same hour?

**Comment by trackermb** [comment]
hi there i have edited 1st post with new screenshot

**Comment by Arcanemagus** [comment]
Those are different days :wink:.

**Comment by trackermb** [comment]
I thought that the max hourly plays would have collated all play @ 10am from all the days so you can see what time the server is under the greatest load.  Is that some that could be edited in a future release?

**Comment by Arcanemagus** [comment]
That's a great point, the chart title doesn't really match the contents. Feel free to submit a PR (to `dev`) that fixes this.

Personally I would recommend looking into [PlexPy](https://github.com/drzoidberg33/plexpy) as it has several architechtural advantages that make it a much better choice for something like this (namely being run as a service instead of a stateless PHP application).
