### ISSUE TITLE
History stopped tracking

### ISSUE THREAD

**Issue by tomhoogeveentje** [ecleese/plexWatchWeb#176]
My plexwatchWeb has stopped tracking the history after 1,044 entries.
When I do a fresh install( i use it in a docker container) it starts tracking again but I would like to keep te rest of the history.

Can anyone help me?

**Comment by Arcanemagus** [comment]
plexWatchWeb is only an interface to the database plexWatch keeps, you might want to ask there?

I've personally moved over to PlexPy as a service is far better suited to this task compared to PHP which must initialize on every page load.

**Comment by tomhoogeveentje** [comment]
I have switched to PLexPy. Looks really good!
