### ISSUE TITLE
Failed to access Plex Media Server. Please check your settings.

### ISSUE THREAD

**Issue by Wonderpants** [ecleese/plexWatchWeb#181]
I updated my Plex to 1.1 last night and immediately after get the Failed to Access. I tried clearning creds then saving, then reentering them and saving but that didn't help.

**Comment by Arcanemagus** [comment]
It's quite possible 1.1 removed something it depended on for authentication. I would _highly_ recommend you look into migrating to [PlexPy](https://github.com/drzoidberg33/plexpy) though as it is far better suited to the task of monitoring a Plex server, and is far more capable than this project ever was.

If you figure out what broke authentication and put up a PR I can merge it for anyone still using this though.

**Comment by Wonderpants** [comment]
Thanks for the response AND for the alternative choice. I'll check out PlexPy.

**Comment by Wonderpants** [comment]
Sweet fancy moses PlexPy is faster and has far more features with a much easier setup. Anyone looking at this should probably just shift there given the support and upkeep.

**Comment by Arcanemagus** [comment]
When building something like this you really need something continuously running to maintain state and not have to re-do a _ton_ of work on every load of a page. PHP doesn't really offer the opportunity for that like Python (or anything else...) does.
