### ISSUE TITLE
Timezone output wrong even though it's set correctly in the php.ini file

### ISSUE THREAD

**Issue by Jynx2120** [ecleese/plexWatchWeb#182]
I installed plexwatchweb on a new Windows 10 server and I set the proper timezone info in the php.ini file and the output times when accessing plexwatch locally are off by 6 hours, ahead of my true time (America/New_York).

I have no idea what to do at this point. I have another server running plexwatchweb almost identical and it runs great and all info is correct.

Any suggestions or help would be greatly appreciated.

**Comment by Arcanemagus** [comment]
This project is deprecated and will receive no further fixes. I _strongly_ recommend you switch to [PlexPy](https://jonnywong16.github.io/plexpy/) as it is far better than this ever was 😉.
