### ISSUE TITLE
[Critical] Local File Inclusion (LFI) vulnerability in includes/img.php

### ISSUE THREAD

**Issue by m33x** [ecleese/plexWatchWeb#74]
Hi 

depending if the 

```
$plexWatch['myPlexAuthToken']
```

is set in the config.php or not, we can access arbitrary files on the local file system. This can be used to hack the server or steal data like myPlex login credentials.

The vulnerability can be found in includes/img.php the HTTP GET parameter "img" can be used to access every file on the filesystem, which is readable by the executing user.
```
$url = $_GET['img'];
$img = file_get_contents($url);
echo $img;
```
even the appending of **"&X-Plex-Token="** can be circumvented by injection a Null-Byte e.g. **"%00"**. (This depend on the used PHP-Version) See http://blog.benjaminwalters.net/?p=22139 for an example.

A fix can not be easily installed, a complete rewrite of this function should be considered, limiting the access to only read from whitelisted remote (HTTPs) sites?

![screen shot 2014-06-13 at 15 40 54](https://cloud.githubusercontent.com/assets/883685/3270697/2834fc02-f303-11e3-9367-19459590c3c5.png)

![screen shot 2014-06-13 at 16 02 49](https://cloud.githubusercontent.com/assets/883685/3270824/3f012a9a-f304-11e3-8893-a0d243004efa.png)

**Comment by ecleese** [comment]
this should be resolved in v1.6.1 dev
