### ISSUE TITLE
"Failed to access plexWatch database. Please check your settings."  after latest plexWatch installed

### ISSUE THREAD

**Issue by fysmd** [ecleese/plexWatchWeb#79]
I just pulled ther latests plexWatch from github (now 0.3.1) and after it ran first time I now get this error in plexWatchWeb.

from settings page (when broken):
Version Information
plexWatch/Web Version: v1.5.4.2
plexWatch Version: v

Reverting plexWatch and DB to 0.2.9 (1d30ab3) version seems to fix it.

.. or should this be reported as a plexWatch issue instead?

**Comment by Ackis** [comment]
Why is write access to the entire directory needed?

**Comment by Arcanemagus** [comment]
SQLite creates two temporary files when accessing a database to store changes... even if none are made. If it is unable to create these temporary files it fails to open the database.

I had hoped to remove this requirement by using the native sqlite3() functions in PHP and setting the connection to read only, but it still creates the files. As PDO is, on average, 2x faster at database operations PWW currently uses that even though it doesn't have an explicit read only mode.
