### ISSUE TITLE
plexWatchWeb home is empty.

### ISSUE THREAD

**Issue by gshlomi** [ecleese/plexWatchWeb#90]
The rest of the tabs are getting updated with currently playing or watched status, but the homepage stays blank...

![image](https://cloud.githubusercontent.com/assets/4084415/5556830/88017a06-8cf1-11e4-9bb5-956f44d17540.png)

![image](https://cloud.githubusercontent.com/assets/4084415/5556835/afe77b6a-8cf1-11e4-9cfa-cd0978a0d1f0.png)

**Comment by ecleese** [comment]
What do your web server logs indicate right after browsing to the index page?

**Comment by gshlomi** [comment]
Removed PlexWatchWeb folder and rebuilt, all works now...
