### ISSUE TITLE
Platform icons not showing

### ISSUE THREAD

**Issue by Deepcuts** [ecleese/plexWatchWeb#91]
For Samsung, the icon is NOT showing.
For Chrome, the icon is showing.
For iOS, the icon is showing.

![untitled](https://cloud.githubusercontent.com/assets/4704834/5606011/4514f8de-9422-11e4-8090-a0bef3513df5.png)

Checked and samsung.png exists in images/platforms/

The code (from user.php) should display the right icon, but it is not.
$platformImage = "images/platforms/samsung.png";

**Comment by ecleese** [comment]
should be fixed in upcoming v1.6.1 dev.

**Comment by Deepcuts** [comment]
Temp fix:

user.php

after line 429 add the code:
}else if(strstr($platformXmlField->Player['platform'], 'Samsung')) {
$platformImage = "images/platforms/samsung.png";


includes/current_activity.php

after line 64 add the code:
}else if(strstr($sessions->Player['platform'], 'Samsung')) {
$platformImage = "images/platforms/samsung.png";


This shows the correct Samsung icon for user page and home page.

**Comment by ecleese** [comment]
this should be resolved in v.1.6.1 dev
