### ISSUE TITLE
Audio not showing in Stats or History

### ISSUE THREAD

**Issue by Deepcuts** [ecleese/plexWatchWeb#92]
i have an audio library.
When a user plays a file, PlexWatchWeb shows the item being played.
But no record of it in either Stats, History or user details.
Movies and TV Shows are displayed everywhere.

**Comment by ecleese** [comment]
This relies on plexWatch to actually track "track" type content. Until it is implemented in plexWatch, plexWatch/Web will not display music history information.

**Comment by Deepcuts** [comment]
10-4. Closing for now.
