### ISSUE TITLE
User with a pin : HTTP 401 Unauthorized

### ISSUE THREAD

**Issue by kschutt** [ecleese/plexWatchWeb#94]
When a user has defined a pin, it causes plexWebWatch to have a 401 Unauthorized when fetching from PMS. (Similar to issue #68)

    PHP Fatal error:  Call to undefined function curl_init() in /var/www/plexWatch/includes/myplex.php on line 19, referer: http://localhost:5579/plexWatch/settings.php
    PHP Warning:  file_get_contents(http://localhost:32400/status/sessions?X-Plex-Token=): failed to open stream: HTTP request failed! HTTP/1.0 401 Unauthorized\r\n in /var/www/plexWatch/index.php on line 88
    PHP Warning:  simplexml_load_file(http://localhost:32400/library/sections): failed to open stream: HTTP request failed! HTTP/1.0 401 Unauthorized\r\n in /var/www/plexWatch/index.php on line 91
    PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity "http://localhost:32400/library/sections" in /var/www/plexWatch/index.php on line 91

**Comment by ecleese** [comment]
If you enabled Plex/Home you need to enter your Plex.tv username and password for plexWatch/Web to be able to access your server.
