### ISSUE TITLE
Failed to access Plex Media Server. Please check your settings.

### ISSUE THREAD

**Issue by odaysawaqed** [ecleese/plexWatchWeb#96]
Plex Server Version 0.9.11.13 (Running on Ubuntu 14.04)
plexWatch/Web Version: v1.5.4.2
plexWatch Version: v0.3.2

Things i tried:
Changing ip address in the settings page to 127.0.0.1, localhost, (my internal ip 10.0.0.5)
Changing permissions for /opt/plexWatch/plexWatch.db
-current user
-root
-www-data

Enabling/disabling Plex Home
Changing the password from the settings page and click on save (some users had luck with that)

I also tried 
sudo chmod 777 /opt/plexWatch && sudo chmod 755 /opt/plexWatch/plexWatch.pl
with no luck

I tried restarting/reloading apache2 to test new settings.
username and password are set for config.pl

I tried with Require authentication on local networks Checked/Unchecked

Any help would be great

Screenshots
==========

Homepage:
![homepage](https://cloud.githubusercontent.com/assets/8609934/6628019/81f93b94-c8d8-11e4-86d4-07f86bfef864.png)

Settings: 
![settings](https://cloud.githubusercontent.com/assets/8609934/6628023/86aed2f2-c8d8-11e4-9b02-d20259625451.png)

Charts:
![charts](https://cloud.githubusercontent.com/assets/8609934/6628027/8ba77d22-c8d8-11e4-8369-d0f4713a6d48.png)

Clicking on a movie title would result in this:
![clicking on movie title](https://cloud.githubusercontent.com/assets/8609934/6628031/8e458e2a-c8d8-11e4-8c20-02c25adad197.png)

**Comment by Arcanemagus** [comment]
Do you see the same issues when using the v1.6.1 dev branch?

**Comment by odaysawaqed** [comment]
I didn't even know there was such release! I thought I downlo the most recent one! I will download/test and update this post!

In regards to the "Secure We Port" I tried both regular and secure with no luck (same issue)!

What's driving me crazy is that most of the features are working. It's inly the home page and the movies posters and links when clicked on them! I honestly think it has something to do with the token but can't figure it out!

**Comment by Clock** [comment]
Some issue here sometimes. All features are working, but homepage is nagging about a failed connection from time to time. Ctrl + F5 a couple of times will fix it, but I have no idea about the real cause.

**Comment by Arcanemagus** [comment]
@Clock Your issue is just a symptom of the way that plexWatch and plexWatch/Web access the same SQLite database. Currently the web interface accesses it in read/write mode which causes some additional delays and makes the probability that you will run into that issue more likely. I have a pull request in that (among many other things) changes it to read only which greatly helps with that issue. With SQLite never really being designed for multi-client access though it will keep happening from time to time.

@odaysawaqed Did you ever get your issue figured out?

**Comment by Clock** [comment]
Thanks for the insights, looking forward to the update! Thanks!

2015-05-26 18:48 GMT+02:00 Landon Abney <notifications@github.com>:

**Comment by Arcanemagus** [comment]
@Clock The changes were merged into the latest dev branch, please try out v1.7.0 and see if the instances of hitting that message go down.

**Comment by Arcanemagus** [comment]
@odaysawaqed Are you still having issues?

**Comment by odaysawaqed** [comment]
@Arcanemagus I'm sorry for the delayed response. I installed the v1.6.1 dev and that seemed to fix the problem instantly.

Thank you.

**Comment by Arcanemagus** [comment]
I'm going to go ahead and close this then. Feel free to start another issue if you run into problems.
